name: Build APK
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup EAS CLI
        run: npm install -g eas-cli

      - name: Process Project
        run: |
          tar -xvf void-rise-mobile.tar.gz
          TARGET_DIR=$(find . -name "package.json" -not -path "*/node_modules/*" -exec dirname {} \;)
          echo "Moving to $TARGET_DIR"
          cd "$TARGET_DIR"
          rm -f package-lock.json
          npm install --no-audit --no-fund
          eas build --platform android --profile preview --local
